name: Build

on:
  push:
    branches: [main, master] #TODO: fix
    tags-ignore: ["[0-9]+.[0-9]+*"]
  workflow_call:

env:
  executable: example

jobs:
  test:
    name: Check & Test
    uses: ./.github/workflows/test.yml

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo run --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/${{ env.executable }} .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ env.executable }}
            README.md
            LICENSE
          name: linux

  build-macos:
    name: macOS
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build (Apple Silicon)
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) \
            MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version) \
            cargo build --release --target aarch64-apple-darwin

      - name: Build (x86 Apple)
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) \
            MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version) \
            cargo build --release --target x86_64-apple-darwin

      - name: Universal Binary
        run: |
          lipo -create -output ${{ env.executable }} \
            target/aarch64-apple-darwin/release/${{ env.executable }} \
            target/x86_64-apple-darwin/release/${{ env.executable }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ env.executable }}
            README.md
            LICENSE
          name: macos


  build-windows:
    name: Windows
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          mv target/x86_64-pc-windows-msvc/release/${{ env.executable }}.exe .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ env.executable }}.exe
            README.md
            LICENSE
          name: win
