name: Check

on: [workflow_call]

jobs:
  general:
    name: General
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Audit
        run: cargo deny --color always --all-features check
        if: ${{ success() || failure() }}

  platform:
    name: ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform: [{id: ubuntu-latest, name: Linux},
                   {id: macos-latest, name: MacOS},
                   {id: windows-latest, name: Windows}]
      fail-fast: false
    runs-on: ${{ matrix.platform.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Check
        run: cargo hack --workspace --feature-powerset --color always check

      - name: Lint
        run: cargo hack --workspace --feature-powerset --color always clippy --no-deps -- -D warnings
        if: ${{ success() || failure() }}
