name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+*"]

env:
  EXECUTABLE: example

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  unixlike:
    name: ${{ target.pretty-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [{id: linux-x86_64, pretty-name: Linux | x86_64 },
                 {id: linux-aarch64, pretty-name: Linux | aarch64 },
                 {id: macos-x86_64, pretty-name: MacOS | x86_64 },
                 {id: macos-aarch64, pretty-name: MacOS | Apple Silicon },
                 {id: macos-universal, pretty-name: MacOS | Universal Binary }]
    needs: build

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: Package
        run: |
          tar xvf builds/${{ target.id }}/out.tar --directory builds/${{ target.id }}
          tar czf ${{ env.EXECUTABLE }}_linux.tar.gz builds/${{ target.id }}/*

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.EXECUTABLE }}-${{ target.id }}.tar.gz
          asset_name: ${{ env.EXECUTABLE }}_${{ steps.tag.outputs.tag }}-${{ target.id }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  windows:
    name: ${{ target.pretty-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [{id: win-gnu, pretty-name: Windows | GNU },
                 {id: win-msvc, pretty-name: Linux | MSVC }]
    needs: build

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: Package
        uses: vimtor/action-zip@v1
        with:
          files: builds/${{ target.id }}
          recursive: false
          dest: ${{ env.EXECUTABLE }}-${{ target.id }}.zip

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.EXECUTABLE }}-${{ target.id }}.zip
          asset_name: ${{ env.EXECUTABLE }}_${{ steps.tag.outputs.tag }}-${{ target.id }}.zip
          tag: ${{ github.ref }}
          overwrite: true
